### ISSUE TITLE
oj.h not found on FreeBSD

### ISSUE THREAD

**Issue by mfechner** [meinac/oj-introspect#4] opened 2022-12-03 07:50 UTC
Hi,

I maintain the gitlab-ce port for the FreeBSD.org system and the new gitlab-ce 15.6 version requires this gem.
I tried now to make a package for but I have problem generating the package, maybe you can help me.

All packages are generated in its own jail and only packages are available that are added before by build/run dependencies (I'm not sure if this is the problem here):
If I try to let the FreeBSD ports system generate the package for oj-introspect I see the following error message:
```
current directory: /wrkdirs/usr/ports/devel/rubygem-oj-introspect/work/stage/usr/local/lib/ruby/gems/3.0/gems/oj-introspect-0.7.1/ext/oj-introspect
make DESTDIR\= sitearchdir\=./.gem.20221203-45844-tsv7wz sitelibdir\=./.gem.20221203-45844-tsv7wz
compiling introspect.c
introspect.c:2:10: fatal error: 'oj.h' file not found
#include "oj.h"
         ^~~~~~
1 error generated.
*** Error code 1

Stop.
make[1]: stopped in /wrkdirs/usr/ports/devel/rubygem-oj-introspect/work/stage/usr/local/lib/ruby/gems/3.0/gems/oj-introspect-0.7.1/ext/oj-introspect
```
You can find the full log here:
https://pkg.fechner.net/data/131amd64-gitlab/2022-12-03_08h36m47s/logs/errors/rubygem-oj-introspect-0.7.1.log

I connected into the jail and search for the file and it is located here:
/usr/ports/devel/rubygem-oj/work/oj-3.13.23/ext/oj/oj.h

So I'm not sure if this problem is related to oj-introspect or if oj just misses to install this oj.h file in a common ruby location.

Thanks a lot for any hint.

Matthias

**Comment by meinac** [comment] 2022-12-04 19:49
Hi Matthias,

> All packages are generated in its own jail and only packages are available that are added before by build/run dependencies (I'm not sure if this is the problem here)

If I understand correctly you already mentioned that the oj.h exists in the system so this might not be the root cause.

You already mentioned that you can access to jail so could you please try compiling manually? If it fails again then we can print some information in extconf.rb or check the generated makefile.

**Comment by mfechner** [comment] 2022-12-05 07:34
> If I understand correctly you already mentioned that the oj.h exists in the system so this might not be the root cause.

yes, but it is maybe not on a standard location and this is the reason why it is maybe not found.

> You already mentioned that you can access to jail so could you please try compiling manually? If it fails again then we can print some information in extconf.rb or check the generated makefile.

I just looked into it, how the gem is generated and FreeBSD is calling the following command:
`(cd /wrkdirs/usr/ports/devel/rubygem-oj-introspect/work/oj-introspect-0.7.1; /usr/bin/env RB_USER_INSTALL=yes LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 /usr/local/bin/gem install -l --no-update-sources --install-dir /wrkdirs/usr/ports/devel/rubygem-oj-introspect/work/stage/usr/local/lib/ruby/gems/3.0 --ignore-dependencies --bindir=/wrkdirs/usr/ports/devel/rubygem-oj-introspect/work/stage/usr/local/bin --no-document oj-introspect-0.7.1.gem -- )`

I attached you the generated Makefile.
[oj-introspect_Makefile.txt](https://github.com/meinac/oj-introspect/files/10151615/oj-introspect_Makefile.txt)

I can also modify the extconf.rb, but I'm not a ruby developer or do know ruby, I just package it ;)
(but I have good knowledge in many programming languages ;) )

I have more the impression that the oj gem does not install the oj.h header file and therefor it is clear that it cannot find it.
The header file is located in the source for oj package in `/usr/ports/devel/rubygem-oj/work/oj-3.13.23/ext/oj/oj.h`

**Comment by meinac** [comment] 2022-12-06 12:21
Thanks for the additional information @mfechner!

I see that the makefile is using `/usr/local/lib/ruby/gems/3.0/gems/oj-3.13.23/ext/oj` folder but the header is located under `/usr/ports/devel/rubygem-oj/work/oj-3.13.23/ext/oj` so I suggest you modify your build script to compile oj-introspect with the `--with-oj-include=/usr/ports/devel/rubygem-oj/work/oj-3.13.23/ext/oj` flag.

I don't know how your build script looks like but the command would be something like this if it was just `gem install`;

`gem install oj-introspect -- --with-oj-include=/usr/ports/devel/rubygem-oj/work/oj-3.13.23/ext/oj`

**Comment by mfechner** [comment] 2022-12-07 09:10
Thanks a lot @meinac for your answer.
I think the first source of the problem is that the rubygem oj does not install the header files. We should be report this to oj package maintainer that the header files are installed and not only the `oj.so`.
I added now a work-around that all header files for oj are included and are available.

I was now able to continue further, but it stops now with the next error message:
```
cd /wrkdirs/usr/ports/devel/rubygem-oj-introspect/work/oj-introspect-0.7.1 ; /usr/bin/env RB_USER_INSTALL=yes LANG=en_US.UTF-8 LC_A
LL=en_US.UTF-8 /usr/local/bin/gem install -l --no-update-sources --install-dir /wrkdirs/usr/ports/devel/rubygem-oj
-introspect/work/stage/usr/local/lib/ruby/gems/3.0 --ignore-dependencies --bindir=/wrkdirs/usr/ports/devel/rubygem
-oj-introspect/work/stage/usr/local/bin --no-document oj-introspect-0.7.1.gem --
Building native extensions. This could take a while...
ERROR:  Error installing oj-introspect-0.7.1.gem:
        ERROR: Failed to build gem native extension.

    current directory: /wrkdirs/usr/ports/devel/rubygem-oj-introspect/work/stage/usr/local/lib/ruby/gems/3.0/gems/
oj-introspect-0.7.1/ext/oj-introspect
/usr/local/bin/ruby30 -I /usr/local/lib/ruby/site_ruby/3.0 extconf.rb
creating Makefile

current directory: /wrkdirs/usr/ports/devel/rubygem-oj-introspect/work/stage/usr/local/lib/ruby/gems/3.0/gems/oj-i
ntrospect-0.7.1/ext/oj-introspect
make DESTDIR\= sitearchdir\=./.gem.20221207-65739-ft6gkg sitelibdir\=./.gem.20221207-65739-ft6gkg clean

current directory: /wrkdirs/usr/ports/devel/rubygem-oj-introspect/work/stage/usr/local/lib/ruby/gems/3.0/gems/oj-i
ntrospect-0.7.1/ext/oj-introspect
make DESTDIR\= sitearchdir\=./.gem.20221207-65739-ft6gkg sitelibdir\=./.gem.20221207-65739-ft6gkg
compiling introspect.c
linking shared-object oj/introspect/introspect_ext.so
ld: error: unknown argument '-U'
ld: error: unknown argument '-U'
ld: error: unknown argument '-U'
ld: error: cannot open _oj_init_usual: No such file or directory
ld: error: cannot open _oj_parser_new: No such file or directory
ld: error: cannot open _oj_parser_set_option: No such file or directory
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1
```

I think it maybe requires a specific compiler, I will check this.

**Comment by meinac** [comment] 2022-12-22 18:49
Hi @mfechner 👋 Did you make any progress on this? Do you need anything else from my side? Otherwise, can we close this issue?

**Comment by mfechner** [comment] 2022-12-23 05:35
@meinac I'm sorry, but the error message while compiling this (see post https://github.com/meinac/oj-introspect/issues/4#issuecomment-1340624073) give you an idea, why it fails to build?
Currently I do not have an idea, why this gem could not be compiled.

I ported 100reds of other modules but this is the first one I see this problem. So any help is welcome.

**Comment by meinac** [comment] 2022-12-23 14:19
@mfechner This gem is following a unique approach to be able to use a header file provided by another gem so I guess that's why you are having problems. Are you able to provide a docker setup that I can pull and debug on my own?

**Comment by vinay-keshava** [comment] 2022-12-24 18:42
Had the same issue on debian,  the header files were not packaged with the gem, modifying the build script to install the header files solved this issue on debian.

**Comment by mfechner** [comment] 2023-01-10 14:01
> @mfechner This gem is following a unique approach to be able to use a header file provided by another gem so I guess that's why you are having problems. Are you able to provide a docker setup that I can pull and debug on my own?

I'm sry, but as I do not work with Linux I cannot provide with a docker setup.

But I was able to fix the problem by just removing the following lines:
```
--- ext/oj-introspect/extconf.rb.orig   2023-01-10 13:31:58 UTC
+++ ext/oj-introspect/extconf.rb
@@ -7,22 +7,6 @@ oj_version_file_path = Pathname.new(oj_version_file)

 OJ_HEADERS = oj_version_file_path.join('..', '..', '..', 'ext', 'oj').to_s

-cc_version = `#{RbConfig.expand("$(CC) --version".dup)}`
-if cc_version.match?(/clang/i)
-  # Ignore symbols loaded from Oj in case Ruby is compiled without
-  # "-Wl,-undefined,dynamic_lookup" (related to https://bugs.ruby-lang.org/issues/19005)
-  symfile = File.join(__dir__, 'oj.sym')
-  dynamic_symbols = File.readlines(symfile)
-  dynamic_symbols.each do |sym|
-    $DLDFLAGS << " -Wl,-U,#{sym.strip}"
-  end
-
-  # Needed for Ruby 3.2 ABI check: https://github.com/ruby/ruby/pull/5474
-  if RUBY_VERSION >= "3.2"
-    $LDFLAGS << " -Wl,-exported_symbol,_ruby_abi_version"
-  end
-end
-
 dir_config('oj', [OJ_HEADERS], [])

 create_makefile("oj/introspect/introspect_ext")
```

**Closed as completed** 2023-01-25 15:16 UTC
